### ISSUE TITLE
The LOCAL_IP replacement is not needed

### ISSUE THREAD

**Issue by mdelapenya** [4lejandrito/liferay-remote-staging-docker#1]
The LOCAL_IP token is not processed by portal source code.

Besides, the RUN command in the Dockerfile is executed on build time, so the IP obtained there is not the real IP used by any running instance of that image.

It actually works because of the SERVER_IP token

**Comment by 4lejandrito** [comment]
Hi @mdelapenya,

LOCAL_IP is a token that is replaced at image build time with the docker host's address. It is not meant to be the instance's own address.

We have to add the host's address to portal.properties to authorise communication with it. This is to allow the remote staging instance (the one in docker) communicate with the local staging instance (the one running on localhost). 

I'll close the issue feel free to reopen it.

**Comment by mdelapenya** [comment]
But that's not totally accurate:

When you are building the image, the RUN instruction reads the IP address of the container **used to build** the image (yes, each layer on an image is built by a underlying docker container), which is completely different that any running instance of the resulting image.

So when you run the container (runtime), the IP of that container is not the same than the one captured on build time.

**Comment by 4lejandrito** [comment]
To be honest I haven't run this for almost a year and maybe something has changed on Docker. But it did work when I needed it and LOCAL_IP was replaced with the host's address.

I'll try again tomorrow to find out if it still works or not.

**Comment by mdelapenya** [comment]
I double checked with @jkappler: the LOCAL_IP is not used across portal's source code. Please check that the replaced IP is not the same that the real IP of the container: 

`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name_or_id
`

**Comment by mdelapenya** [comment]
So I guess that it works because that LOCAL_IP is not used for the staging communication
